server:
  port: 8080

spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: orderuser
    password: orderpass123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

order:
  worker:
    maxRetries: 3
    failureProbability: 0.33
    processingDelayMs: 500
    retryDelayMs: 1000
  events:
    mode: sqs

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - correlationId=%X{correlationId} %msg%n"
  level:
    software.amazon.awssdk: DEBUG
aws:
  region: eu-west-1
  sqs:
    #endpoint: http://localhost:4566
    #queueUrl: http://localhost:4566/000000000000/order-events
    queueUrl: "https://sqs.eu-west-1.amazonaws.com/583880312081/order-platform-aws-lab-order-events"

