spring:
  application:
    name: worker
  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: orderuser
    password: orderpass123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - correlationId=%X{correlationId} %msg%n"

worker:
  outbox:
    lockTimeoutSeconds: 30
  mode: sqs-consumer
  sqs:
    poll:
      delay-ms: 1000

aws:
  region: eu-west-1
  sqs:
    endpoint: http://localhost:4566
    queueUrl: http://localhost:4566/000000000000/order-events
order:
  worker:
    maxRetries: 3
    retryDelayMs: 1000
    failureProbability: 0.3


